ALTER TABLE users ADD COLUMN created TIMESTAMP;
ALTER TABLE users ALTER COLUMN created SET DEFAULT now();
ALTER TABLE users ADD COLUMN updated TIMESTAMP;
ALTER TABLE users ALTER COLUMN updated SET DEFAULT now();
ALTER TABLE roles ADD COLUMN created TIMESTAMP;
ALTER TABLE roles ALTER COLUMN created SET DEFAULT now();
ALTER TABLE roles ADD COLUMN updated TIMESTAMP;
ALTER TABLE roles ALTER COLUMN updated SET DEFAULT now();
